name: flutter_turorial
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.12
  freezed_annotation: ^1.1.0
  retrofit: ^3.0.1
  logging: ^1.0.2
  pretty_dio_logger: ^1.1.1
  flutter_riverpod: ^1.0.3
  flutter_state_notifier: ^0.7.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  freezed: ^1.1.1
  retrofit_generator: ^4.0.1
  json_serializable: ^6.1.4

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

